spring:
  exposed:
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://kroong.iptime.org:55432/kotlinblog
    username: kroong